### ISSUE TITLE
When I run your code on my ipad pro there is a problem

### ISSUE THREAD

**Issue by stevewongv** [stfnjstn/iPadSwiftPlayground#1]
ios 10b2 when run my code ipad told me there is a problem encountered. Can you fix that?

**Comment by stfnjstn** [comment]
Tried to fix it without success. Since beta 2 it is not possible to create SKShapeNode or SKSpriteNote. It crashes during setting the size property. I fear we have to wait for beta 3

**Comment by stfnjstn** [comment]
The SpriteKit issue has been fixed in iOS 10 Beta 5. I've also updated the playground to the latest SWIFT syntax
